development:
  adapter: postgresql
  encoding: unicode
  database: rails_flashcards_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_flashcards_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rails_flashcards
  pool: 5
  password:
